The name "pandas" is derived from __panel data__, an econometrics term for multidimensional structured datasets.

---

__Pandas__ is a data analysis toolkit __built on top of NumPy__, designed to handle __tabular data__ (i.e., data with rows and columns) efficiently. It offers two primary data structures:
- `Series`: a one-dimensional labeled array (like a column of data).
- `DataFrame`: a two-dimensional table with labeled axes (rows and columns).

---

## Pandas Series

A __Series__ in pandas is a one-dimensional labeled array that can hold any data type (integers, floats, strings, etc.). You can think of a Series as a __column of data__ with an index. Each value in a Series has an __index label__, which defaults to integers 0, 1, 2, ... but can be set to other values (like dates or strings) to label each data point.

**Creating a Series:** You can create a Series from a list, NumPy array, scalar value, or a Python dictionary.

In [2]:
import pandas as pd

In [2]:
sales = pd.Series([10, 20, 30])
sales

0    10
1    20
2    30
dtype: int64

In [3]:
# We can also specify a custom index:
salesQ1 = pd.Series([10, 20, 30], index=['Jan', 'Feb', 'Mar'])
salesQ1

Jan    10
Feb    20
Mar    30
dtype: int64

The `dtype: int64` at the bottom indicates the data type of the Series (64-bit integer in this case).

In [4]:
# we can retrieve values by these labels:
salesQ1['Feb']

20

In [5]:
sales[1]

20

However, be careful: if your Series has a numeric index (e.g., 0,1,2 as labels), `series_obj[1]` will refer to the label `1`, which in this case is also the second element. With a non-integer index (like 'Jan', 'Feb'), `series_obj[1]` will instead get the item at position 1 (because label 1 doesn't exist). To avoid confusion between label-based and position-based indexing, pandas provides __`.loc`__ (label-based) and __`.iloc`__ (integer position-based) accessors. For a Series, `s.loc[label]` and `s.iloc[position]` can be used explicitly.

---

**Series from a dictionary:** If you create a Series from a dict, the keys become the index labels and the values become the data:

In [6]:
grades = pd.Series({'Alice': 85, 'Bob': 90, 'Charlie': 95})
grades

Alice      85
Bob        90
Charlie    95
dtype: int64

In [7]:
print(grades['Bob'])

90

Notice how similar this is to looking up a value by key in a dictionary, but the Series provides additional functionality and compatibility with other pandas operations.

---

**Basic operations on Series:** Pandas Series support vectorized operations and NumPy functions. For example, you can do arithmetic on a Series across all elements at once:

In [8]:
sales

0    10
1    20
2    30
dtype: int64

In [9]:
double_sales = sales * 2
double_sales

0    20
1    40
2    60
dtype: int64

Similarly, many NumPy functions will work element-wise on Series:

In [10]:
import numpy as np
print(np.log(sales))   # natural log of each sales value

0    2.302585
1    2.995732
2    3.401197
dtype: float64

Pandas will align operations by index, meaning if you have two Series with the same index, you can add or subtract them and pandas will match values by the index labels.

> **Tip:** A Series is like a **column** in a table. But if you print a Series, it looks similar to a column with its index. If you get output that looks like `Name: <something>, dtype: <type>` at the end, that indicates it's a Series (with that name and data type). If you accidentally put an extra set of brackets when selecting data from a DataFrame (e.g., `df[['col']]`), you might get a DataFrame instead of Series. Remember: single bracket `df['col']` -> Series, double brackets `df[['col']]` -> DataFrame.

---
---

## Pandas DataFrame

__Creating DataFrames:__
1. __From a dictionary of lists:__

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['NY', 'LA', 'Chicago', 'NY', 'LA']
}
df = pd.DataFrame(data)
df

      Name  Age     City
0    Alice   24       NY
1      Bob   27       LA
2  Charlie   22  Chicago
3    David   32       NY
4      Eva   29       LA

2. __From a list of dictionaries:__

In [12]:
data_list = [
    {'Name': 'Alice', 'Age': 24, 'City': 'NY'},
    {'Name': 'Bob', 'Age': 27, 'City': 'LA'},
    {'Name': 'Charlie', 'Age': 22, 'City': 'Chicago'}
]
df2 = pd.DataFrame(data_list)
df2

      Name  Age     City
0    Alice   24       NY
1      Bob   27       LA
2  Charlie   22  Chicago

In [13]:
df2.shape

(3, 3)

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

---

In [15]:
df

      Name  Age     City
0    Alice   24       NY
1      Bob   27       LA
2  Charlie   22  Chicago
3    David   32       NY
4      Eva   29       LA

In [17]:
df['Age'] # this will give the Series corresponding to the "Age" column

0    24
1    27
2    22
3    32
4    29
Name: Age, dtype: int64

In [18]:
df[['Age']] # double brackets -> DataFrame

   Age
0   24
1   27
2   22
3   32
4   29

In [19]:
# If you need multiple columns, pass a list of column names:
df[['Name', 'City']]

      Name     City
0    Alice       NY
1      Bob       LA
2  Charlie  Chicago
3    David       NY
4      Eva       LA

---

__By row index:__ Pandas uses the `.loc` and `.iloc` accessors for rows.

- `df.loc[index_label]` selects a row by the __index label__.
- `df.iloc[index_position]` selects a row by the __integer position__ (similar to how Python list indexing works).

In [21]:
df

      Name  Age     City
0    Alice   24       NY
1      Bob   27       LA
2  Charlie   22  Chicago
3    David   32       NY
4      Eva   29       LA

In [22]:
df.loc[2]

Name    Charlie
Age          22
City    Chicago
Name: 2, dtype: object

In [23]:
df.loc[2]['Age']

22

In [24]:
df.iloc[2]

Name    Charlie
Age          22
City    Chicago
Name: 2, dtype: object

---

You can also select a subset of rows and columns together by using `df.loc[row_index, col_index]`. For instance, `df.loc[0:2, ['Name', 'Age']]` would give a DataFrame of rows 0 through 2 (inclusive) with only the Name and Age columns.

In [22]:
df

      Name  Age     City
0    Alice   24       NY
1      Bob   27       LA
2  Charlie   22  Chicago
3    David   32       NY
4      Eva   29       LA

In [24]:
df.loc[0:2, ['Name', 'Age']]

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22

Because `.loc` is __label-based__, and __label slices are inclusive__ in pandas.

- `0:2` refers to __index labels__, not positions
- pandas includes __both the start and the end label__
- So you get rows with index 0, 1, and 2 → __3 rows__

#### Compare with `.iloc` (position-based)

In [25]:
df.iloc[0:2, ['Name', 'Age']]

IndexError: .iloc requires numeric indexers, got ['Name' 'Age']

IndexError: .iloc requires numeric indexers, got ['Name' 'Age']

In [26]:
df.iloc[0:2, [0, 1]]

    Name  Age
0  Alice   24
1    Bob   27

- `.iloc` works like normal Python slicing
- __End is exclusive__
- Returns rows at positions __0 and 1 only__

---

__Slicing:__ Similar to Python lists, you can slice DataFrame rows by index. `df[1:4]` will give rows with index 1, 2, 3 (note: when slicing with `df[start:stop]` the stop is excluded, just like normal Python slicing). However, it's often clearer to use .iloc for slicing by position or .loc for slicing by label range.

In [26]:
df

      Name  Age     City
0    Alice   24       NY
1      Bob   27       LA
2  Charlie   22  Chicago
3    David   32       NY
4      Eva   29       LA

`df[1:4] → also POSITION-based`

In [27]:
df[1:4]

      Name  Age     City
1      Bob   27       LA
2  Charlie   22  Chicago
3    David   32       NY

- Pandas treats it like Python slicing
- So it behaves like `.iloc`

📌 Rule

`df[a:b]` = position slicing = end is excluded

> **Tip**: Remember that `.loc` is label-based and includes the end of the slice, whereas `.iloc` is position-based and works like typical Python slicing (excluding the end). For example, if your index is 0...4, `df.loc[0:2]` returns indices 0,1,2 inclusive, while `df.iloc[0:2]` returns indices 0,1. This is a common source of confusion for beginners.

**DataFrame vs Series output:** Selecting a single column or a single row yields a Series. Selecting multiple columns or multiple rows yields a DataFrame. Keep this in mind, as operations and available methods can differ between Series and DataFrames.

In [27]:
df.loc[0]

Name    Alice
Age        24
City       NY
Name: 0, dtype: object

---
---

### Data Types and Type Conversion

`df.dtypes` or `df.info()`

Common pandas dtypes include `int64` (integer), `float64` (float), `object` (typically strings or mixed types), `bool` (boolean), `datetime64` (dates and times), etc.

In [4]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

---

Sometimes, you may need to **convert data types**. For instance, a column of numbers might be read as strings (object dtype), or a numeric column might need to be converted to categorical type to save memory.

- To **convert** a column’s type, use `astype`. For example, if `df['Age']` were read as strings, we could do `df['Age'] = df['Age'].astype(int)` to convert it to integers.
- Pandas also provides `pd.to_datetime()` to convert a date string column to actual datetime objects, `pd.to_numeric()` to force convert strings to numbers (useful if some values are non-numeric), and `astype('category')` to convert to categorical type.

In [7]:
# Suppose Age is read as string, convert to numeric
df['Age'] = df['Age'].astype('int64')

df['City'] = df['City'].astype('category')

In [8]:
df.dtypes

Name      object
Age        int64
City    category
dtype: object

In this example, `City` became a categorical type, which can be more memory-efficient if there are only a few unique cities.

> **Tip:** If you have numeric data stored as strings (e.g., `"25"` instead of 25), use `pd.to_numeric(df['col'], errors='coerce')` to convert them. The `errors='coerce'` will turn non-convertible strings into NaN. This is a handy way to clean columns with mixed types.

---
---

### Basic DataFrame Operations

In [9]:
df

      Name  Age     City
0    Alice   24       NY
1      Bob   27       LA
2  Charlie   22  Chicago
3    David   32       NY
4      Eva   29       LA

In [11]:
# This is sometimes called boolean indexing:

df[df['Age'] > 25]

    Name  Age City
1    Bob   27   LA
3  David   32   NY
4    Eva   29   LA

BUT remember to wrap each condition in parentheses. For example:

In [12]:
df[(df['Age'] > 25) & (df['City'] == 'NY')]

    Name  Age City
3  David   32   NY

---

#### Sorting

`df.sort_values()`

`ascending=False` for descending order

In [13]:
df.sort_values('Age', ascending=False)

      Name  Age     City
3    David   32       NY
4      Eva   29       LA
1      Bob   27       LA
0    Alice   24       NY
2  Charlie   22  Chicago

In [14]:
df.sort_values(['City', 'Age'])

      Name  Age     City
2  Charlie   22  Chicago
1      Bob   27       LA
4      Eva   29       LA
0    Alice   24       NY
3    David   32       NY

---

### Arithmetic on Columns and Creating New Columns

Pandas allows vectorized arithmetic operations on columns. For example, you can add, subtract, multiply, divide entire columns (Series) by other columns or scalars.

In [16]:
# Create a new column based on existing ones
df['AgeNextYear'] = df['Age'] + 1
print(df[['Name' , 'Age', 'AgeNextYear']])

      Name  Age  AgeNextYear
0    Alice   24           25
1      Bob   27           28
2  Charlie   22           23
3    David   32           33
4      Eva   29           30

If we had another numeric column, we could do element-wise operations. For instance, imagine a `df['Sales']` and `df['Costs']`, then `df['Profit'] = df['Sales'] - df['Costs']` would compute profit for each row.

---

### Summary Statistics

- __Single aggregation functions:__ You can call methods like `.mean()`, `.median()`, `.sum()`, `.min()`, `.max()`, etc., on a Series (or numeric DataFrame columns) to get that statistic.

In [18]:
print('Average age:', df['Age'].mean())
print('Max age:', df['Age'].max())

Average age: 26.8
Max age: 32

- __`.describe()` method:__ This is a handy function that gives a bunch of statistics at once for numeric columns:

In [19]:
df.describe()

             Age  AgeNextYear
count   5.000000     5.000000
mean   26.800000    27.800000
std     3.962323     3.962323
min    22.000000    23.000000
25%    24.000000    25.000000
50%    27.000000    28.000000
75%    29.000000    30.000000
max    32.000000    33.000000

In [20]:
df

      Name  Age     City  AgeNextYear
0    Alice   24       NY           25
1      Bob   27       LA           28
2  Charlie   22  Chicago           23
3    David   32       NY           33
4      Eva   29       LA           30

In [21]:
df.describe(include='all')

         Name        Age City  AgeNextYear
count       5   5.000000    5     5.000000
unique      5        NaN    3          NaN
top     Alice        NaN   LA          NaN
freq        1        NaN    2          NaN
mean      NaN  26.800000  NaN    27.800000
std       NaN   3.962323  NaN     3.962323
min       NaN  22.000000  NaN    23.000000
25%       NaN  24.000000  NaN    25.000000
50%       NaN  27.000000  NaN    28.000000
75%       NaN  29.000000  NaN    30.000000
max       NaN  32.000000  NaN    33.000000

> __Note:__ By default, these operations skip missing values. For instance, `mean()` will calculate the mean of available (non-missing) values. We will cover missing data handling next.

---

### Modifying Data

You can modify values in the DataFrame by assignment:

In [22]:
df

      Name  Age     City  AgeNextYear
0    Alice   24       NY           25
1      Bob   27       LA           28
2  Charlie   22  Chicago           23
3    David   32       NY           33
4      Eva   29       LA           30

In [24]:
# Single value
df.loc[0, 'Age'] = 25

In [25]:
# A column
df['Age'] = df['Age'] + 1

In [26]:
# A slice or a subset
df.loc[df['Name'] == 'Bob', 'City'] = 'San Francisco'

TypeError: Cannot setitem on a Categorical with a new category (San Francisco), set the categories first

When a column is `category`, **pandas locks the allowed values** (categories).

✅ Solution 1: Add the category first (recommended)

In [28]:
df['City'] = df['City'].cat.add_categories(['San Francisco'])

In [29]:
df

      Name  Age     City  AgeNextYear
0    Alice   26       NY           25
1      Bob   28       LA           28
2  Charlie   23  Chicago           23
3    David   33       NY           33
4      Eva   30       LA           30

In [32]:
df.loc[df['Name'] == 'Bob', 'City'] = 'San Francisco'

In [33]:
df

      Name  Age           City  AgeNextYear
0    Alice   26             NY           25
1      Bob   28  San Francisco           28
2  Charlie   23        Chicago           23
3    David   33             NY           33
4      Eva   30             LA           30

✅ Solution 2: Rename categories (cleanest if it's a replacement)

In [35]:
# If "SF" already exists and you’re just renaming it:
df['City'] = df['City'].cat.rename_categories({'San Francisco': 'SF'})

In [36]:
df['City'].unique()

['NY', 'SF', 'Chicago', 'LA']
Categories (4, object): ['Chicago', 'LA', 'NY', 'SF']

In [37]:
df

      Name  Age     City  AgeNextYear
0    Alice   26       NY           25
1      Bob   28       SF           28
2  Charlie   23  Chicago           23
3    David   33       NY           33
4      Eva   30       LA           30

✅ Solution 3: Temporarily convert to string (quick & dirty)

In [38]:
df['City'] = df['City'].astype(str)
df.loc[df['Name'] == 'Bob', 'City'] = 'Sacramento'
df['City'] = df['City'].astype('category')

In [39]:
df['City'].unique()

['NY', 'Sacramento', 'Chicago', 'LA']
Categories (4, object): ['Chicago', 'LA', 'NY', 'Sacramento']

In [40]:
df

      Name  Age        City  AgeNextYear
0    Alice   26          NY           25
1      Bob   28  Sacramento           28
2  Charlie   23     Chicago           23
3    David   33          NY           33
4      Eva   30          LA           30

---
---

### Handling Missing Data

Pandas uses `NaN` (Not a Number) as the default marker for missing values (you may also see `None` in object-type columns, which pandas typically treats as NaN under the hood).

__Detecting missing data:__

- `df.isna()` or `df.isnull()` returns a DataFrame of booleans of the same shape, with True indicating a missing value.

- `df.notna()` or `df.notnull()` does the opposite.

- You can chain `.sum()` to count missing values per column (since True will be treated as 1 in a sum):

In [41]:
df.isnull().sum()

Name           0
Age            0
City           0
AgeNextYear    0
dtype: int64

---

In [44]:
data = {
    'Name': ['Tom', 'Jane', 'Steve'],
    'Score': [90, None, 85],    # Jane's score is missing (None -> NaN)
    'Grade': [None, 'B', 'A']   # Tom's grade is missing
}
df2 = pd.DataFrame(data)
print(df2)

    Name  Score Grade
0    Tom   90.0  None
1   Jane    NaN     B
2  Steve   85.0     A

---

In pandas, missing values can be indicated by **three main markers**:

1️⃣ `NaN` (`numpy.nan`)

- The __standard__ missing value marker in pandas

- Used mainly for **numeric data**

- IEEE floating-point “Not a Number”

In [46]:
import numpy as np
np.nan

nan

In [47]:
pd.isna(np.nan)

True

---

2️⃣ `None`

- Python’s native null object

- Common in **object dtype** columns

- Pandas usually __converts it to `NaN` internally__

In [48]:
pd.isna(None)

True

Important detail:

- In __object columns__, `None` may stay as `None`
- In __numeric columns__, `None` → `NaN`

---

3️⃣ `pd.NA` (often forgotten, but important!)

- Introduced for __nullable pandas dtypes__

- Used with:
    - Int64, Float64
    - string
    - boolean
    - category

In [49]:
pd.NA

In [51]:
pd.isna(pd.NA)

True

This is pandas’ “official” missing value for modern dtypes.

⚠️ Also:

In [60]:
pd.NA == pd.NA # “Comparison with missing is unknown”

In [55]:
np.nan == np.nan # False

False

---

❌ Old behavior (without pd.NA)

In [56]:
s = pd.Series([1, 2, None])

In [57]:
s

0    1.0
1    2.0
2    NaN
dtype: float64

💥 Problem:

- Integers turned into floats

✅ New behavior (with pd.NA)

In [58]:
s = pd.Series([1, 3, pd.NA], dtype='Int64')
s

0       1
1       3
2    <NA>
dtype: Int64

In [59]:
s.isna()

0    False
1    False
2     True
dtype: bool

---

### Mental model (remember this)

- `NaN` → numeric hack (float-based)
- `None` → Python object
- `pd.NA` → pandas’ official, dtype-aware missing value

If you remember only one thing, remember this:

> If you see `<NA>` and __a capitalized dtype__ like `Int64` or `string`, you’re dealing with `pd.NA`.


---